on:
  schedule:
    - cron:  '0 2 * * 2'

name: Scrape-data

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: data

      - name: Update data
        run: |
          source("data-raw/semaforos.R")
        shell: Rscript {0}

      - name: Commit latest data
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git add inst/extdata/semaforos.csv
          git commit -m "Fetch latest semaforos data"
          git pull --rebase origin main
          git push
          echo "pushed to github"

  # https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/7
  trigger-deploy:
    needs: fetch-data
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Trigger pkgdown.yaml workflow
        run: |
          gh workflow run pkgdown.yaml
