on:
  schedule:
    - cron:  '0 2 * * 2'

name: Scrape-data

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: data

      - name: Update data
        run: |
          source("data-raw/semaforos.R")
        shell: Rscript {0}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data
          file_pattern: inst/extdata/semaforos.csv

  # https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/7
  trigger-deploy:
    needs: fetch-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger pkgdown.yaml workflow
        run: |
          gh workflow run pkgdown.yaml
